
version: 0.2

env:

  parameter-store:
    key: "BACKEND_URL"


phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
    - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
    - npm install
  build:
    commands:
      - echo "Build Sequence……"
      - echo "BACKEND_URL=$key" >> .env
      - npm run build
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - /tmp/node_modules.tar

